# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nick/project/CubeMX/Clion_MAX_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nick/project/CubeMX/Clion_MAX_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/project/CubeMX/Clion_MAX_test/CMakeFiles /home/nick/project/CubeMX/Clion_MAX_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/project/CubeMX/Clion_MAX_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UPLOAD

# Build rule for target.
UPLOAD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UPLOAD
.PHONY : UPLOAD

# fast build rule for target.
UPLOAD/fast:
	$(MAKE) -f CMakeFiles/UPLOAD.dir/build.make CMakeFiles/UPLOAD.dir/build
.PHONY : UPLOAD/fast

#=============================================================================
# Target rules for targets named Clion_MAX_test.elf

# Build rule for target.
Clion_MAX_test.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Clion_MAX_test.elf
.PHONY : Clion_MAX_test.elf

# fast build rule for target.
Clion_MAX_test.elf/fast:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/build
.PHONY : Clion_MAX_test.elf/fast

App/MAX7219.obj: App/MAX7219.cpp.obj

.PHONY : App/MAX7219.obj

# target to build an object file
App/MAX7219.cpp.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/App/MAX7219.cpp.obj
.PHONY : App/MAX7219.cpp.obj

App/MAX7219.i: App/MAX7219.cpp.i

.PHONY : App/MAX7219.i

# target to preprocess a source file
App/MAX7219.cpp.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/App/MAX7219.cpp.i
.PHONY : App/MAX7219.cpp.i

App/MAX7219.s: App/MAX7219.cpp.s

.PHONY : App/MAX7219.s

# target to generate assembly for a file
App/MAX7219.cpp.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/App/MAX7219.cpp.s
.PHONY : App/MAX7219.cpp.s

App/MAX7219_MatrixDisplay.obj: App/MAX7219_MatrixDisplay.cpp.obj

.PHONY : App/MAX7219_MatrixDisplay.obj

# target to build an object file
App/MAX7219_MatrixDisplay.cpp.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/App/MAX7219_MatrixDisplay.cpp.obj
.PHONY : App/MAX7219_MatrixDisplay.cpp.obj

App/MAX7219_MatrixDisplay.i: App/MAX7219_MatrixDisplay.cpp.i

.PHONY : App/MAX7219_MatrixDisplay.i

# target to preprocess a source file
App/MAX7219_MatrixDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/App/MAX7219_MatrixDisplay.cpp.i
.PHONY : App/MAX7219_MatrixDisplay.cpp.i

App/MAX7219_MatrixDisplay.s: App/MAX7219_MatrixDisplay.cpp.s

.PHONY : App/MAX7219_MatrixDisplay.s

# target to generate assembly for a file
App/MAX7219_MatrixDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/App/MAX7219_MatrixDisplay.cpp.s
.PHONY : App/MAX7219_MatrixDisplay.cpp.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.s

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.obj: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.obj

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.obj

# target to build an object file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.obj
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.obj

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.i: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.i

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.i

# target to preprocess a source file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.i
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.i

Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.s: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.s

.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.s

# target to generate assembly for a file
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.s
.PHONY : Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.s

Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.obj: Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.obj

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.obj

# target to build an object file
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.obj
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.obj

Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.i: Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.i

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.i

# target to preprocess a source file
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.i
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.i

Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.s: Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.s

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.s

# target to generate assembly for a file
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.s
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c.s

Middlewares/Third_Party/FreeRTOS/Source/croutine.obj: Middlewares/Third_Party/FreeRTOS/Source/croutine.c.obj

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/croutine.obj

# target to build an object file
Middlewares/Third_Party/FreeRTOS/Source/croutine.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/croutine.c.obj
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/croutine.c.obj

Middlewares/Third_Party/FreeRTOS/Source/croutine.i: Middlewares/Third_Party/FreeRTOS/Source/croutine.c.i

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/croutine.i

# target to preprocess a source file
Middlewares/Third_Party/FreeRTOS/Source/croutine.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/croutine.c.i
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/croutine.c.i

Middlewares/Third_Party/FreeRTOS/Source/croutine.s: Middlewares/Third_Party/FreeRTOS/Source/croutine.c.s

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/croutine.s

# target to generate assembly for a file
Middlewares/Third_Party/FreeRTOS/Source/croutine.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/croutine.c.s
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/croutine.c.s

Middlewares/Third_Party/FreeRTOS/Source/event_groups.obj: Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.obj

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/event_groups.obj

# target to build an object file
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.obj
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.obj

Middlewares/Third_Party/FreeRTOS/Source/event_groups.i: Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.i

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/event_groups.i

# target to preprocess a source file
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.i
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.i

Middlewares/Third_Party/FreeRTOS/Source/event_groups.s: Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.s

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/event_groups.s

# target to generate assembly for a file
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.s
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/event_groups.c.s

Middlewares/Third_Party/FreeRTOS/Source/list.obj: Middlewares/Third_Party/FreeRTOS/Source/list.c.obj

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/list.obj

# target to build an object file
Middlewares/Third_Party/FreeRTOS/Source/list.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/list.c.obj
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/list.c.obj

Middlewares/Third_Party/FreeRTOS/Source/list.i: Middlewares/Third_Party/FreeRTOS/Source/list.c.i

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/list.i

# target to preprocess a source file
Middlewares/Third_Party/FreeRTOS/Source/list.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/list.c.i
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/list.c.i

Middlewares/Third_Party/FreeRTOS/Source/list.s: Middlewares/Third_Party/FreeRTOS/Source/list.c.s

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/list.s

# target to generate assembly for a file
Middlewares/Third_Party/FreeRTOS/Source/list.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/list.c.s
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/list.c.s

Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.obj: Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.obj

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.obj

# target to build an object file
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.obj
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.obj

Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.i: Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.i

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.i

# target to preprocess a source file
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.i
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.i

Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.s: Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.s

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.s

# target to generate assembly for a file
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.s
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c.s

Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.obj: Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.obj

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.obj

# target to build an object file
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.obj
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.obj

Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.i: Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.i

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.i

# target to preprocess a source file
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.i
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.i

Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.s: Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.s

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.s

# target to generate assembly for a file
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.s
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c.s

Middlewares/Third_Party/FreeRTOS/Source/queue.obj: Middlewares/Third_Party/FreeRTOS/Source/queue.c.obj

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/queue.obj

# target to build an object file
Middlewares/Third_Party/FreeRTOS/Source/queue.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/queue.c.obj
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/queue.c.obj

Middlewares/Third_Party/FreeRTOS/Source/queue.i: Middlewares/Third_Party/FreeRTOS/Source/queue.c.i

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/queue.i

# target to preprocess a source file
Middlewares/Third_Party/FreeRTOS/Source/queue.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/queue.c.i
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/queue.c.i

Middlewares/Third_Party/FreeRTOS/Source/queue.s: Middlewares/Third_Party/FreeRTOS/Source/queue.c.s

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/queue.s

# target to generate assembly for a file
Middlewares/Third_Party/FreeRTOS/Source/queue.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/queue.c.s
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/queue.c.s

Middlewares/Third_Party/FreeRTOS/Source/tasks.obj: Middlewares/Third_Party/FreeRTOS/Source/tasks.c.obj

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/tasks.obj

# target to build an object file
Middlewares/Third_Party/FreeRTOS/Source/tasks.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/tasks.c.obj
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/tasks.c.obj

Middlewares/Third_Party/FreeRTOS/Source/tasks.i: Middlewares/Third_Party/FreeRTOS/Source/tasks.c.i

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/tasks.i

# target to preprocess a source file
Middlewares/Third_Party/FreeRTOS/Source/tasks.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/tasks.c.i
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/tasks.c.i

Middlewares/Third_Party/FreeRTOS/Source/tasks.s: Middlewares/Third_Party/FreeRTOS/Source/tasks.c.s

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/tasks.s

# target to generate assembly for a file
Middlewares/Third_Party/FreeRTOS/Source/tasks.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/tasks.c.s
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/tasks.c.s

Middlewares/Third_Party/FreeRTOS/Source/timers.obj: Middlewares/Third_Party/FreeRTOS/Source/timers.c.obj

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/timers.obj

# target to build an object file
Middlewares/Third_Party/FreeRTOS/Source/timers.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/timers.c.obj
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/timers.c.obj

Middlewares/Third_Party/FreeRTOS/Source/timers.i: Middlewares/Third_Party/FreeRTOS/Source/timers.c.i

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/timers.i

# target to preprocess a source file
Middlewares/Third_Party/FreeRTOS/Source/timers.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/timers.c.i
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/timers.c.i

Middlewares/Third_Party/FreeRTOS/Source/timers.s: Middlewares/Third_Party/FreeRTOS/Source/timers.c.s

.PHONY : Middlewares/Third_Party/FreeRTOS/Source/timers.s

# target to generate assembly for a file
Middlewares/Third_Party/FreeRTOS/Source/timers.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Middlewares/Third_Party/FreeRTOS/Source/timers.c.s
.PHONY : Middlewares/Third_Party/FreeRTOS/Source/timers.c.s

Src/exemple.obj: Src/exemple.cpp.obj

.PHONY : Src/exemple.obj

# target to build an object file
Src/exemple.cpp.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/exemple.cpp.obj
.PHONY : Src/exemple.cpp.obj

Src/exemple.i: Src/exemple.cpp.i

.PHONY : Src/exemple.i

# target to preprocess a source file
Src/exemple.cpp.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/exemple.cpp.i
.PHONY : Src/exemple.cpp.i

Src/exemple.s: Src/exemple.cpp.s

.PHONY : Src/exemple.s

# target to generate assembly for a file
Src/exemple.cpp.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/exemple.cpp.s
.PHONY : Src/exemple.cpp.s

Src/freertos.obj: Src/freertos.c.obj

.PHONY : Src/freertos.obj

# target to build an object file
Src/freertos.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/freertos.c.obj
.PHONY : Src/freertos.c.obj

Src/freertos.i: Src/freertos.c.i

.PHONY : Src/freertos.i

# target to preprocess a source file
Src/freertos.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/freertos.c.i
.PHONY : Src/freertos.c.i

Src/freertos.s: Src/freertos.c.s

.PHONY : Src/freertos.s

# target to generate assembly for a file
Src/freertos.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/freertos.c.s
.PHONY : Src/freertos.c.s

Src/gpio.obj: Src/gpio.c.obj

.PHONY : Src/gpio.obj

# target to build an object file
Src/gpio.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/gpio.c.obj
.PHONY : Src/gpio.c.obj

Src/gpio.i: Src/gpio.c.i

.PHONY : Src/gpio.i

# target to preprocess a source file
Src/gpio.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/gpio.c.i
.PHONY : Src/gpio.c.i

Src/gpio.s: Src/gpio.c.s

.PHONY : Src/gpio.s

# target to generate assembly for a file
Src/gpio.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/gpio.c.s
.PHONY : Src/gpio.c.s

Src/main.obj: Src/main.c.obj

.PHONY : Src/main.obj

# target to build an object file
Src/main.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/main.c.obj
.PHONY : Src/main.c.obj

Src/main.i: Src/main.c.i

.PHONY : Src/main.i

# target to preprocess a source file
Src/main.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/main.c.i
.PHONY : Src/main.c.i

Src/main.s: Src/main.c.s

.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/main.c.s
.PHONY : Src/main.c.s

Src/spi.obj: Src/spi.c.obj

.PHONY : Src/spi.obj

# target to build an object file
Src/spi.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/spi.c.obj
.PHONY : Src/spi.c.obj

Src/spi.i: Src/spi.c.i

.PHONY : Src/spi.i

# target to preprocess a source file
Src/spi.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/spi.c.i
.PHONY : Src/spi.c.i

Src/spi.s: Src/spi.c.s

.PHONY : Src/spi.s

# target to generate assembly for a file
Src/spi.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/spi.c.s
.PHONY : Src/spi.c.s

Src/stm32f4xx_hal_msp.obj: Src/stm32f4xx_hal_msp.c.obj

.PHONY : Src/stm32f4xx_hal_msp.obj

# target to build an object file
Src/stm32f4xx_hal_msp.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/stm32f4xx_hal_msp.c.obj
.PHONY : Src/stm32f4xx_hal_msp.c.obj

Src/stm32f4xx_hal_msp.i: Src/stm32f4xx_hal_msp.c.i

.PHONY : Src/stm32f4xx_hal_msp.i

# target to preprocess a source file
Src/stm32f4xx_hal_msp.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/stm32f4xx_hal_msp.c.i
.PHONY : Src/stm32f4xx_hal_msp.c.i

Src/stm32f4xx_hal_msp.s: Src/stm32f4xx_hal_msp.c.s

.PHONY : Src/stm32f4xx_hal_msp.s

# target to generate assembly for a file
Src/stm32f4xx_hal_msp.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/stm32f4xx_hal_msp.c.s
.PHONY : Src/stm32f4xx_hal_msp.c.s

Src/stm32f4xx_hal_timebase_TIM.obj: Src/stm32f4xx_hal_timebase_TIM.c.obj

.PHONY : Src/stm32f4xx_hal_timebase_TIM.obj

# target to build an object file
Src/stm32f4xx_hal_timebase_TIM.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/stm32f4xx_hal_timebase_TIM.c.obj
.PHONY : Src/stm32f4xx_hal_timebase_TIM.c.obj

Src/stm32f4xx_hal_timebase_TIM.i: Src/stm32f4xx_hal_timebase_TIM.c.i

.PHONY : Src/stm32f4xx_hal_timebase_TIM.i

# target to preprocess a source file
Src/stm32f4xx_hal_timebase_TIM.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/stm32f4xx_hal_timebase_TIM.c.i
.PHONY : Src/stm32f4xx_hal_timebase_TIM.c.i

Src/stm32f4xx_hal_timebase_TIM.s: Src/stm32f4xx_hal_timebase_TIM.c.s

.PHONY : Src/stm32f4xx_hal_timebase_TIM.s

# target to generate assembly for a file
Src/stm32f4xx_hal_timebase_TIM.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/stm32f4xx_hal_timebase_TIM.c.s
.PHONY : Src/stm32f4xx_hal_timebase_TIM.c.s

Src/stm32f4xx_it.obj: Src/stm32f4xx_it.c.obj

.PHONY : Src/stm32f4xx_it.obj

# target to build an object file
Src/stm32f4xx_it.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/stm32f4xx_it.c.obj
.PHONY : Src/stm32f4xx_it.c.obj

Src/stm32f4xx_it.i: Src/stm32f4xx_it.c.i

.PHONY : Src/stm32f4xx_it.i

# target to preprocess a source file
Src/stm32f4xx_it.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/stm32f4xx_it.c.i
.PHONY : Src/stm32f4xx_it.c.i

Src/stm32f4xx_it.s: Src/stm32f4xx_it.c.s

.PHONY : Src/stm32f4xx_it.s

# target to generate assembly for a file
Src/stm32f4xx_it.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/stm32f4xx_it.c.s
.PHONY : Src/stm32f4xx_it.c.s

Src/system_stm32f4xx.obj: Src/system_stm32f4xx.c.obj

.PHONY : Src/system_stm32f4xx.obj

# target to build an object file
Src/system_stm32f4xx.c.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/system_stm32f4xx.c.obj
.PHONY : Src/system_stm32f4xx.c.obj

Src/system_stm32f4xx.i: Src/system_stm32f4xx.c.i

.PHONY : Src/system_stm32f4xx.i

# target to preprocess a source file
Src/system_stm32f4xx.c.i:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/system_stm32f4xx.c.i
.PHONY : Src/system_stm32f4xx.c.i

Src/system_stm32f4xx.s: Src/system_stm32f4xx.c.s

.PHONY : Src/system_stm32f4xx.s

# target to generate assembly for a file
Src/system_stm32f4xx.c.s:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/Src/system_stm32f4xx.c.s
.PHONY : Src/system_stm32f4xx.c.s

startup/startup_stm32f429xx.obj: startup/startup_stm32f429xx.s.obj

.PHONY : startup/startup_stm32f429xx.obj

# target to build an object file
startup/startup_stm32f429xx.s.obj:
	$(MAKE) -f CMakeFiles/Clion_MAX_test.elf.dir/build.make CMakeFiles/Clion_MAX_test.elf.dir/startup/startup_stm32f429xx.s.obj
.PHONY : startup/startup_stm32f429xx.s.obj

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... UPLOAD"
	@echo "... Clion_MAX_test.elf"
	@echo "... App/MAX7219.obj"
	@echo "... App/MAX7219.i"
	@echo "... App/MAX7219.s"
	@echo "... App/MAX7219_MatrixDisplay.obj"
	@echo "... App/MAX7219_MatrixDisplay.i"
	@echo "... App/MAX7219_MatrixDisplay.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.s"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.obj"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.i"
	@echo "... Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.s"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.obj"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.i"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.s"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/croutine.obj"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/croutine.i"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/croutine.s"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/event_groups.obj"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/event_groups.i"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/event_groups.s"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/list.obj"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/list.i"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/list.s"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.obj"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.i"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.s"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.obj"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.i"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.s"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/queue.obj"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/queue.i"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/queue.s"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/tasks.obj"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/tasks.i"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/tasks.s"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/timers.obj"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/timers.i"
	@echo "... Middlewares/Third_Party/FreeRTOS/Source/timers.s"
	@echo "... Src/exemple.obj"
	@echo "... Src/exemple.i"
	@echo "... Src/exemple.s"
	@echo "... Src/freertos.obj"
	@echo "... Src/freertos.i"
	@echo "... Src/freertos.s"
	@echo "... Src/gpio.obj"
	@echo "... Src/gpio.i"
	@echo "... Src/gpio.s"
	@echo "... Src/main.obj"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
	@echo "... Src/spi.obj"
	@echo "... Src/spi.i"
	@echo "... Src/spi.s"
	@echo "... Src/stm32f4xx_hal_msp.obj"
	@echo "... Src/stm32f4xx_hal_msp.i"
	@echo "... Src/stm32f4xx_hal_msp.s"
	@echo "... Src/stm32f4xx_hal_timebase_TIM.obj"
	@echo "... Src/stm32f4xx_hal_timebase_TIM.i"
	@echo "... Src/stm32f4xx_hal_timebase_TIM.s"
	@echo "... Src/stm32f4xx_it.obj"
	@echo "... Src/stm32f4xx_it.i"
	@echo "... Src/stm32f4xx_it.s"
	@echo "... Src/system_stm32f4xx.obj"
	@echo "... Src/system_stm32f4xx.i"
	@echo "... Src/system_stm32f4xx.s"
	@echo "... startup/startup_stm32f429xx.obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

